Connected/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]    

core/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    #path('account/', include('core.urls.')),
    path('home/',views.index, name='home'),
    #path('',views.index, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('u/<str:username>/', views.ProfileView, name='profile'),
    path('u/<str:username>/update', views.update_profile, name='profile-update'),
    path('temp/',views.temp, name='temp'),
    path('u/<str:username>/follow', views.follow, name='follow'),
    path('u/<str:username>/create_post',views.create_post,name='create_post'),
    path('u/<str:username>/<int:post_id>/create_comment',views.create_comment,name='create_comment'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
#from django_mysql.models import ListCharField


# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	college = models.CharField(max_length = 100)
	location = models.CharField(max_length = 100)
	bio = models.TextField(max_length = 1000)
	birth_date = models.CharField(max_length = 100)
	#followers = models.ListCharField(base_field= models.CharField(max_length= 50), size=100, max_length=5500)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Followers(models.Model):
	profile = models.ForeignKey(Profile, on_delete= models.CASCADE)
	follower_name = models.CharField(max_length= 50)

class Following(models.Model):
	profile = models.ForeignKey(Profile, on_delete= models.CASCADE)
	following_name = models.CharField(max_length= 50)	

class Post(models.Model):
	heading =models.TextField(max_length=100)
	content  = models.TextField(max_length=5000)
	profile = models.ForeignKey(Profile, on_delete= models.CASCADE, blank=True)

class Comments(models.Model):
	post = models.ForeignKey(Post, on_delete =models.CASCADE, blank=True)
	content = models.TextField(max_length=5000)
	commenter = models.TextField(max_length=50)	

	

core/forms.py
from django.contrib.auth.models import User
from . models import Profile,Post,Comments
from django import forms



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location', 'birth_date', 'college']

       
class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields=['heading', 'content']


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields=['content']		

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UserForm, ProfileForm, PostForm,CommentForm
from django.db import transaction
from .models import Followers
from . models import Following, Post, Comments
#from .models import Profile
#from .models import UserProfile

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data['username']
            raw_password = form.cleaned_data['password1']
            user = authenticate(username=username, password=raw_password)
            login(request,user)
            return redirect('core:home')
    else:
        form = UserCreationForm()
    return render(request,'core/signup.html', {'form': form})        



def index(request):
    return render(request, 'core/home.html')

@login_required
def temp(request):
    return redirect('core:profile', username= request.user.username )


@login_required
def ProfileView(request, username):
    if username == request.user.username:
        user  = User.objects.get(username=username)
        following= request.user.profile.following_set.all()
        feeds  = Post.objects.all()
        comments= Comments.objects.all()
        return render(request, 'core/profile.html',{'user' : user, 'following': following, 'feeds':feeds, 'comments':comments} )

    else :
        user  = User.objects.get(username=username)
        feeds  = Post.objects.all()
        return render(request, 'core/other_profile.html',{'user' : user, 'feeds':feeds} )






@login_required
#@transaction.atomic
def update_profile(request, username):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('core:profile', username=username)
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'core/profile_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })   


@login_required
def follow(request, username):
    request.user.profile.following_set.create(following_name= username)
    return redirect('core:profile', username=username)


@login_required
def create_post(request,username):
    if request.method=='POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post=post_form.save(commit=False)
            
            a= User.objects.get(username=username)
            post.profile=a.profile
            # post.heading = post_form.heading
            # post.content = post_form.content
            #post_form.heading = request.POST['heading']
            #post_form.content = request.POST['content']
            post.save()
            #post_form.save()
            
            #messages.success(request, 'Your profile was successfully updated!')
            return redirect('core:profile', username=username)
    else:
        post_form=PostForm()
    return render(request,'core/post.html',{'post_form':post_form})            


@login_required
def create_comment(request,username,post_id):
    post=Post.objects.get(pk=post_id)
    if request.method=='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment=comment_form.save(commit=False)
            post=Post.objects.get(id=post_id)
            a=Post.objects.get(id=post_id)
            comment.post=a
            comment.commenter=username
            # post.heading = post_form.heading
            # post.content = post_form.content
            #post_form.heading = request.POST['heading']
            #post_form.content = request.POST['content']
            comment.save()
            #post_form.save()
            
            #messages.success(request, 'Your profile was successfully updated!')
            return redirect('core:profile', username=username)
    else:
        comment_form=CommentForm()
        #post=Post.objects.get(pk=post_id)
    return render(request,'core/comment.html',{'post':post, 'comment_form':comment_form}) 


















# class UserProfileCreate(generic.edit.CreateView):
#      model = UserProfile    
#      fields = ['FirstName', 'LastName', 'email', 'college']
#      success_url = reverse_lazy('core:home')

templates/core/UserProfile_form.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h2>Profile</h2>
	<form action="" method="post">
		{% csrf_token %}
		{% include 'core/form_template.html' %}
		<button type="Submit">Create</button>
	</form>
	
</body>
</html>

templates/core/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Create Comment</title>
</head>
<body>
	<h3>Create Comment</h3>
	
	<form method="POST" action="{% url 'core:create_comment' user.username  post.pk  %}">
	{% csrf_token %}

	{{ comment_form.as_p }}	
	<button type="Submit">Create Comment</button>
	</form>
</body>
</html>

templates/core/form_template.html
{% for field in form %}
{{ form.errors }}

{{ field.label_tag }}
{{ field }}
<br><br>
{% endfor %}

templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	{% if user.is_authenticated %}
	<h3>Hi {{ user.username }}</h3>
	<a href="{% url 'core:logout' %}">Logout</a>	
	{% else %}
	<a href="{% url 'core:login' %}">Login</a>
	<a href="{% url 'core:signup' %}">Signup</a>
	{% endif %}
</body>
</html>

templates/core/login.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <!-- <link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" /> -->
    <!-- Generated: 2018-04-16 09:29:05 +0200 -->
    <title>Login - Connected - a responsive, awesome and full featured social networking site</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <!-- <script src="./assets/js/require.min.js"></script>
    <script>
      requirejs.config({
          baseUrl: '.'
      });
    </script> -->
    <!-- Dashboard Core -->
    <link href="{% static 'assets/css/dashboard.css' %}" rel="stylesheet " />
    <!-- <script src="./assets/js/dashboard.js"></script> --> 
    <!-- c3.js Charts Plugin -->
    <!-- <link href="./assets/plugins/charts-c3/plugin.css" rel="stylesheet" />
    <script src="./assets/plugins/charts-c3/plugin.js"></script> -->
    <!-- Google Maps Plugin -->
    <!-- <link href="./assets/plugins/maps-google/plugin.css" rel="stylesheet" />
    <script src="./assets/plugins/maps-google/plugin.js"></script> -->
    <!-- Input Mask Plugin -->
    <!-- <script src="./assets/plugins/input-mask/plugin.js"></script> -->
  </head>
  <body class="">
    <div class="page">
      <div class="page-single">
        <div class="container">
          <div class="row">
            <div class="col col-login mx-auto">
              <div class="text-center mb-6">
                <img src="./assets/brand/tabler.svg" class="h-6" alt="">
              </div>
              <form class="card" action="" method="post">
                {% csrf_token %}
                <div class="card-body p-6">
                  <div class="card-title">Login to your account</div>
                  {% for field in form %}
                    
                      {% ifequal field.name 'username' %}
                        <div class="form-group">
                        <label class="form-label">Username</label>
                        {% render_field field class+="form-control" placeholder="Username" %}
                        </div>
                      {% endifequal %}
                       
                      {% ifequal field.name 'password' %} 
                        <div class="form-group">
                        <label class="form-label">
                          Password
                        <!-- <a href="./forgot-password.html" class="float-right small">I forgot password</a> -->
                        </label>
                        {% render_field field type="password" class+="form-control" id="exampleInputPassword1" placeholder="Password"%}
                        </div>
                      {% endifequal %}
                  {% endfor %}
                  <div class="form-group">
                    <!-- <label class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" />
                      <span class="custom-control-label">Remember me</span>
                    </label> -->
                  </div>
                  <div class="form-footer">
                    <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                  </div>
                </div>
              </form>
              <div class="text-center text-muted">
                Don't have account yet? <a href="{% url 'core:signup' %}">Sign up</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/core/login1.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
</head>
<body>
	<h3>Log In</h3>
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Log In</button>
	</form>


</body>
</html>

templates/core/other_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Profile</title>
</head>
<body>
	<h2>This is  {{ user.username }}'s Profile 
		<form action="{% url 'core:follow' user.username %}" method='post'>
		{% csrf_token %}
			<button type="Submit">Follow</button>
			
		</form>
	</h2> 
	<!-- <a href="{% url 'core:profile-update' user.username %}">Update Profile</a> -->
<ul>
  <li>Username: {{ user.username }}</li>
  <li>Location: {{ user.profile.location }}</li>
  <li>Birth Date: {{ user.profile.birth_date }}</li>
</ul>

<p>
<!-- 	{% if feeds %} -->
	<h3>Feed:</h3>
	{% for feed in feeds %}
	{{ feed.heading }}
	<p>{{ feed.content }}</p>
	<br>
	{% endfor %}
	<!-- {% endif %} -->

</p>

	<a href="{% url 'core:logout'  %}">Logout</a>
</body>
</html>

templates/core/post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Create Post</title>
</head>
<body>
	<h3>Create Post</h3>
	
	<form method="POST" action="{% url 'core:create_post' user.username %}">
	{% csrf_token %}

	{{ post_form.as_p }}	
	<button type="Submit">Create Post</button>
	</form>
</body>
</html>

templates/core/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Profile</title>
</head>
<body>
	<h2>Hi {{ user.username }}</h2> 
	<a href="{% url 'core:profile-update' user.username %}">Update Profile</a>
<ul>
  <li>Username: {{ user.username }}</li>
  <li>Location: {{ user.profile.location }}</li>
  <li>Birth Date: {{ user.profile.birth_date }}</li>
</ul>
{% if following %}
<h3>Following:
	
		{% for name in following %}
	 {{ name.following_name }}&nbsp
	{% endfor %}
	{% endif %}
	
</h3>

<h4>
	<!-- {% if feeds %} -->
	Feed:
	{% for feed in feeds %}
	{{ feed.heading }}
	{{ feed.content }}
	{% for comment in comments %}
		{% ifequal comment.id feed.id %}
		{{ comment.content }}
		{% endifequal %}
	{% endfor %}	
	<form action="{% url 'core:create_comment' user.username feed.id %}" method='post'>
		{% csrf_token %}
			<button type="Submit">Add Comment</button>
			
		</form>
	{% endfor %}
	<!-- {% endif %} -->

</h4>

	<a href="{% url 'core:logout'  %}">Logout</a>



</body>
</html>

templates/core/profile_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Edit Profile</title>
</head>
<body>
	<form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Save changes</button>
</form>
</body>
</html>

templates/core/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>

 <h3>Sign up</h3>

  <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
  
</body>
</html>